fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User

    from_email:
        address: "%env(EMAIL_FROM_ADDRESS)%"
        sender_name: "%env(EMAIL_FROM_NAME)%"

    registration:
        form:
            type: App\Form\RegistrationFormType

    profile:
        form:
            type: App\Form\ProfileFormType